plugins:
  add_chat_user_enabled:
    default: false
    client: true
  add_chat_user_supervisor_username:
    default: ""
    type: string
  add_chat_user_restrict_dm_to_staff:
    default: false
    client: true
